apiVersion: 1

datasources:
  - name: Habits
    type: postgres
    access: proxy
    url: postgres:5432
    database: habits
    user: habits
    secureJsonData:
      password: habits_secret
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
